services:
  app:
    build:
      context: ./app
    ports:
      - "187:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
    depends_on:
      - db

  cmd:
    build:
      context: ./cmd
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
